# Generated by Django 2.2.5 on 2020-02-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.FileField(upload_to='images/')),
                ('registration', models.URLField()),
                ('organizerEmail', models.EmailField(max_length=254)),
                ('deadline', models.DateTimeField()),
                ('eventType', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('onCampus', models.BooleanField()),
                ('hasFood', models.BooleanField()),
                ('isPrice', models.BooleanField()),
            ],
        ),
    ]
