# Generated by Django 2.2.5 on 2020-02-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='faculty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='hasFood',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='isPrice',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='onCampus',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='registration',
            field=models.URLField(null=True),
        ),
    ]
