# Generated by Django 2.2.5 on 2020-02-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0002_auto_20200215_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='isPrice',
            new_name='isFree',
        ),
    ]
