# Generated by Django 2.2.5 on 2020-02-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0003_auto_20200215_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='picture',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
