# Generated by Django 2.2.5 on 2020-02-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0004_auto_20200215_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('organizerEmail', models.EmailField(max_length=254)),
                ('description', models.TextField(null=True)),
                ('registration', models.URLField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('eventType', models.CharField(max_length=255, null=True)),
                ('faculty', models.CharField(max_length=255, null=True)),
                ('onCampus', models.BooleanField(null=True)),
                ('hasFood', models.BooleanField(null=True)),
                ('isFree', models.BooleanField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
